name: nilcano
version: "1.0"
license: "GPL-2.0-or-later"
date: 2025-04-18
description: |
    Canonical conjugacy representatives in nilpotent groups

authors:
    - name: Óscar Fernández Ayala
      url: https://osferay.github.io

maintainers:
    - name: Óscar Fernández Ayala
      url: https://osferay.github.io

GAP: ">= 4.13"

www: https://osferay.github.io/nilcano/
readme: README.md
packageinfo: https://osferay.github.io/nilcano/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/osferay/nilcano/releases/download/v1.0/nilcano-1.0.tar.gz

abstract: |

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    nilpotent groups, conjugacy problem.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>FA25</span>]   <b class='BibAuthor'>Fernández Ayala, Ó.</b>,
     <i class='BibTitle'>nilcano, Canonical conjugacy representatives in nilpotent groups,
             Version 1.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://osferay.github.io/nilcano/">https://osferay.github.io/nilcano/</a></span>.
    </p>
    

bibtex: |
    @misc{ nilcano,
      author =           {Fern{\a'a}ndez Ayala, {\a'O}.},
      title =            {{nilcano}, {Canonical conjugacy representatives in nilpotent groups}, {V}ersion 1.0},
      month =            {Apr},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href  {https://osferay.github.io/nilcano/} {\texttt{https://osferay.github.io/}\discretionary
                          {}{}{}\texttt{nilcano/}}},
      keywords =         {nilpotent groups; conjugacy problem},
      printedkey =       {FA25}
    }

